name: Check Code Quality
on: [push, pull_request]
env:
  PUBLIC_APIURL: ${{ vars.PUBLIC_APIURL }}
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website-frontend
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
      - name: Install missing packages and dependencies
        run: |
          pnpm install
      - name: Run Prettier check
        if: ${{ !cancelled() }}
        run: pnpm run lint:prettier-only
      - name: Run ESLint
        if: ${{ !cancelled() }}
        run: pnpm run lint:eslint-only
      - name: Run Svelte check
        if: ${{ !cancelled() }}
        run: pnpm run check
